definitions:
  user.LoginRequestDTO:
    properties:
      email:
        type: string
      otp:
        type: string
    required:
    - email
    type: object
  user.RegisterUserDTO:
    description: Payload to register a user
    properties:
      email:
        type: string
      firstName:
        type: string
      lastName:
        type: string
      otp:
        type: string
    required:
    - email
    type: object
  user.SendOTPRequestDTO:
    properties:
      email:
        type: string
      subject:
        type: string
    required:
    - email
    type: object
  user.VerifyOTPRequestDTO:
    properties:
      email:
        type: string
      otp:
        type: string
    type: object
info:
  contact: {}
paths:
  /api/v1/healthCheck:
    get:
      consumes:
      - application/json
      description: Check if the API is running
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            additionalProperties:
              type: string
            type: object
      summary: Health Check
      tags:
      - health
  /api/v1/users/login:
    post:
      consumes:
      - application/json
      description: This endpoint allows users to log in using their email or user
        tag and password. It returns a JWT token upon successful authentication.
      parameters:
      - description: Login request data
        in: body
        name: loginRequest
        required: true
        schema:
          $ref: '#/definitions/user.LoginRequestDTO'
      produces:
      - application/json
      responses:
        "200":
          description: User successfully logged in with JWT token
          schema:
            additionalProperties: true
            type: object
        "400":
          description: Invalid request payload
          schema:
            additionalProperties:
              type: string
            type: object
        "401":
          description: User not found or invalid email/password
          schema:
            additionalProperties:
              type: string
            type: object
        "500":
          description: Internal server error
          schema:
            additionalProperties:
              type: string
            type: object
      summary: User login
      tags:
      - Users
  /api/v1/users/register:
    post:
      consumes:
      - application/json
      description: Registers a new user with email and password
      parameters:
      - description: User registration data
        in: body
        name: request
        required: true
        schema:
          $ref: '#/definitions/user.RegisterUserDTO'
      produces:
      - application/json
      responses:
        "201":
          description: User created successfully with authentication token
          schema:
            additionalProperties:
              type: string
            type: object
        "400":
          description: Invalid request payload
          schema:
            additionalProperties:
              type: string
            type: object
        "401":
          description: Invalid OTP
          schema:
            additionalProperties:
              type: string
            type: object
        "409":
          description: Email already exists
          schema:
            additionalProperties:
              type: string
            type: object
        "500":
          description: Internal server error
          schema:
            additionalProperties:
              type: string
            type: object
      summary: Register User
      tags:
      - Users
  /api/v1/users/sendOtp:
    post:
      consumes:
      - application/json
      description: This endpoint sends a one-time password (OTP) to the specified
        user's email for verification.
      parameters:
      - description: Email Address
        in: body
        name: request
        required: true
        schema:
          $ref: '#/definitions/user.SendOTPRequestDTO'
      produces:
      - application/json
      responses:
        "200":
          description: OTP sent to email
          schema:
            additionalProperties:
              type: string
            type: object
        "400":
          description: Invalid request payload
          schema:
            additionalProperties:
              type: string
            type: object
        "500":
          description: Failed to send OTP
          schema:
            additionalProperties:
              type: string
            type: object
      summary: Send OTP to user's email
      tags:
      - Users
  /api/v1/users/verify:
    post:
      consumes:
      - application/json
      description: This endpoint verifies the OTP sent to the user's email.
      parameters:
      - description: Email and OTP
        in: body
        name: request
        required: true
        schema:
          $ref: '#/definitions/user.VerifyOTPRequestDTO'
      produces:
      - application/json
      responses:
        "200":
          description: OTP verified
          schema:
            additionalProperties:
              type: string
            type: object
        "400":
          description: Invalid request payload
          schema:
            additionalProperties:
              type: string
            type: object
        "401":
          description: OTP verification failed
          schema:
            additionalProperties:
              type: string
            type: object
      summary: Verify OTP
      tags:
      - Users
swagger: "2.0"
