info:
  contact: {}
paths:
  /healthCheck:
    get:
      consumes:
      - application/json
      description: Check if the API is running
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            additionalProperties:
              type: string
            type: object
      summary: Health Check
      tags:
      - health
  /register:
    post:
      consumes:
      - application/json
      description: Registers a new user with email and password
      parameters:
      - description: User registration details
        in: body
        name: request
        required: true
        schema:
          additionalProperties:
            type: string
          type: object
      produces:
      - application/json
      responses:
        "201":
          description: Created
          schema:
            additionalProperties:
              type: string
            type: object
      summary: Register User
      tags:
      - user
swagger: "2.0"
